version: 1.0.0-{build}

os: Visual Studio 2015

nuget:
  account_feed: true

branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

init:
- git config --global core.autocrlf true

before_build:
- cmd: dotnet restore --no-cache

build_script:
- cmd: dotnet build src/Serilog.Sinks.LiteDB -c Release

after_build:
- cmd: dotnet pack src/Serilog.Sinks.LiteDB -o artifacts -c Release

artifacts:
- path: 'artifacts/**/*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: If/9VF8y71yT3VTht3PHFdwohtdZ38PDEIYriNu7gE/VyJRyzqvTdszut0E2Uwoq
  skip_symbols: true
  on:
    branch: master